
- name: criando a chave devops para aws 
  ec2_key:
     name: devopsdays
     aws_access_key: "{{ lookup('env','AWS_ACCESS_KEY' ) }}"
     aws_secret_key: "{{ lookup('env','AWS_SECREY_KEY') }}" 
     region:  us-east-2
     key_material: "{{ lookup('file', '/etc/ansible/devops.pem.pub') }}"
